site_name: 'test'
nav:
  - Home:
    - Home: home/home.md
  - Documentation:
    - Documentation: documentation/documentation.md
  - Getting Started:
    - Getting Started: getting-started/getting-started.md
  - Support:
    - Support: support/support.md

repo_name: 'test'
repo_url: 'https://github.optum.com/ssangwan004/test'
edit_uri: 'blob/master/docs'
copyright: 'Copyright &copy; 2022 Optum'
theme:
  name: material
  palette:
    primary: 'optum orange'
    accent: 'optum orange'
  features:
    - navigation.instant
    - navigation.tabs
  custom_dir: 'theme'
  favicon: img/favicon.ico
  logo: img/optum-white.png
  font:
    text: Arial
    code: Roboto Mono
extra_css:
  - styles/optum-theme.css
plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
